mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "root"
  dbname: "ranking"
  charset: "utf8mb4"
  local: "Local"
  max_idle_time: 20
  max_open_conns: 1024
  max_idle_conns: 20


redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  db: 0
